spring:
  application:
    name: spring-boot-lab
  datasource:
    url: jdbc:postgresql://localhost:5432/finance_tracker
    username: finance_user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
jwt:
  secret: z6AaovapckhRyuf17zAM3wvjdr3LncORjMde5cFjkRo
  expiration: 3600000

logging:
  level:
    org:
      springframework:
        security: DEBUG

